#! /bin/sh

sxhkd &
clipster -d &
polybar bar1 &

bspc monitor -d 0 1 2 3 4

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Eclipse desktop=^3
bspc rule -a Java desktop=^3
bspc rule -a Firefox desktop=^2
bspc rule -a jetbrains-pycharm desktop=^3
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Chromium desktop=^2
